# Generated by Django 2.2.3 on 2019-07-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190707_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(max_length=95, null=True),
        ),
    ]
