# Generated by Django 2.2.3 on 2019-07-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190707_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='created',
            new_name='created_at',
        ),
    ]
