# Generated by Django 2.2.3 on 2019-07-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190707_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='category',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_contacts', to='backend.Vendor'),
        ),
    ]
