# Generated by Django 2.2.3 on 2019-07-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_fieldschema_modelschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldschema',
            name='thing2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='modelschema',
            name='thing',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
