# Generated by Django 2.2.3 on 2019-07-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190709_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldSchema',
        ),
        migrations.DeleteModel(
            name='ModelSchema',
        ),
    ]
