# Generated by Django 2.2.3 on 2019-07-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190710_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortype',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
