# Generated by Django 2.2.3 on 2019-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_project_projectcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
