# Generated by Django 2.2.3 on 2019-07-19 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0012_project_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontact',
            name='project',
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='projects',
            field=models.ManyToManyField(to='backend.Project'),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
