# Generated by Django 2.2.3 on 2019-07-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20190719_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontact',
            name='projects',
            field=models.ManyToManyField(related_name='contact_list', to='backend.Project'),
        ),
    ]
