# Generated by Django 2.2.3 on 2019-07-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20190719_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerclientconfig',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
