# Generated by Django 2.2.3 on 2019-07-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_plannerclientconfig_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='general_notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
