# Generated by Django 2.2.3 on 2019-07-27 13:34

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20190726_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='vendor_attachments',
            field=models.ManyToManyField(to='backend.Vendor'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='attachments',
            field=backend.models.GM2MField(through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
    ]
