# Generated by Django 2.2.3 on 2019-07-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20190728_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
