# Generated by Django 2.2.4 on 2019-08-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_projecttask_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-days_before_event']},
        ),
    ]
