# Generated by Django 2.2.4 on 2019-08-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20190803_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
    ]
