# Generated by Django 2.2.4 on 2019-08-06 12:22

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    ProjectTask = apps.get_model('backend', 'ProjectTask')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(ProjectTask)
    ProjectTask.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)

    Task = apps.get_model('backend', 'Task')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(Task)
    Task.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0030_auto_20190806_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttask',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='templatetask',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='task',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_backend.task_set+', to='contenttypes.ContentType'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
